### DISCUSSION TITLE
Injection status when container does not exist

### DISCUSSION THREAD

**Discussion by rimbesat** [DataDog/chaos-controller#752] [Ideas, user requests and proposals]
Hi team! 

Just wanted to share an issue we face with how we implement the controller. This particular scenario happens if we input a manifest that specifies a container name that does not exist in that pod.

The experiment is defined as the following:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: cpu-pressure-pod
  namespace: chaos-engineering-framework
  annotations:
    chaos.datadoghq.com/environment: "dev"
spec:
  level: pod
  duration: 2m
  selector:
    app.kubernetes.io/name: "fault-injection-showcase"
    app: "fault-injection-showcase--plugin-master"
  containers: 
    - "fault-injection-showcase-does-not-exist" 
  count: 100%
  cpuPressure: 
    count: 100% 
  staticTargeting: true
```

When running this we are inspecting the `injectionStatus` field to determine the status of the experiment and when the experiment ends. This is used in our CI/CD platform and helps us feedback to the user. However, this field does not exist at the start of the experiment and still does not exist when the experiment duration completes, which is leaving us in a waiting state for the injectionStatus to update.

(start)
![image](https://github.com/DataDog/chaos-controller/assets/93604675/9f60f235-f04d-4dfe-9bbd-654af72562fd)
(end)
![image](https://github.com/DataDog/chaos-controller/assets/93604675/105ea3de-4443-4054-9599-f2016ead27fb)

For reference, this is the behaviour of 7.13.1, where at the start of the experiment the field does not exist, and at the end of the experiment the field does exist and states `PreviouslyInjected` which at least allows us to determine the end of the disruption

(start)
![image](https://github.com/DataDog/chaos-controller/assets/93604675/13b629d0-e38a-49b7-8750-3182f6270730)
(end)
![image](https://github.com/DataDog/chaos-controller/assets/93604675/d94c8e3e-6a0d-4512-a9ce-7eee03648c72)

Ideally, we would like this field to be initialised in a NotInjected state, or any other suggestions are welcome.
