### DISCUSSION TITLE
Cloud Disruptions Feature

### DISCUSSION THREAD

**Discussion by rimbesat** [DataDog/chaos-controller#813] [Q&A]
Hi team, we recently enabled the cloud network disruptions, and we had a few questions on how this works since we weren't able to see the effects of the datadog services cloud disruptions. (however we were able to see observations from aws disruptions)
We ran the following experiment:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-cloud
  namespace: chaos-engineering-framework
spec:
  level: pod
  selector:
    app: "fault-injection-showcase--plugin-master"
  count: 100%
  duration: 10m
  network:
    cloud:
       datadog:
        - service: "apm"
    drop: 100 
```
and what we expected to see, was zero apm metrics for this application, though we didn't see any difference in our graphs. We also tried the datadog service as "agents" but still weren't able to see a difference in our metrics. The disruption did inject and could not see any other errors. 

I just wanted some additional clarification about how this feature works. We were using [this page ](https://github.com/DataDog/chaos-controller/blob/main/docs/network_disruption/cloud-managed-services.md) but if could get more information on this, it would be really helpful.

Thanks!
