### ISSUE TITLE
Inaccurate comment in node_failure?

### ISSUE THREAD

**Issue by noqcks** [DataDog/chaos-controller#223]
Hi, quick question.

In node_failure.yaml the namespace metadata has a comment about a disruption resource needing to be in the same namespace as a targeted pod. I don't think this is accurate, because we're not targeting a pod, right? Or does chaos-controller require you to target pods with a label selector and then the nodes backing those pods are put into failure mode?
```
metadata:
  name: disruption-sample
  namespace: chaos-engineering # disruption resource must be in the same namespace as targeted pods
spec:
  selector: # label selector to target pods
    app: demo
```
For node level disruptions, can disruptions be run in any namespace?

Thanks, a little confused.
