### ISSUE TITLE
User Issue: Pod level network disruptions not working

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#351]
**Describe the bug**
I have been trying the pod level network disruptions over the last days but I can't see any impact.
I have Istio installed but I disabled it for the time being to rule that factor out.

**To Reproduce**
First, I deployed the demo resources from this repo. I only changed the namespace to `chaos` as I'm using that one.

**Logs from the demo-curl pod before the disruption**
<img width="954" alt="Screenshot 2021-06-23 at 15 43 09" src="https://user-images.githubusercontent.com/6031527/123117615-cfd50280-d439-11eb-9902-32ab520c3590.png">

**Disruption**
If I understand that correctly the below disruption should impact the egress traffic, i.e. the call from demo curl to Nginx:
```json
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-ingress
  namespace: chaos-engineering
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  network:
    drop: 100
    hosts:
      - port: 80
```

**Logs from the injector pod**
The disruption gets injected:
```
{"level":"info","ts":1624459766542.497,"caller":"injector/main.go:154","message":"injector targeting container","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss","containerID":"docker://ce9300286ab80bd1c76d7deeb1b0a4883cefb33788fc005cd8d4a7992e888d80","container name":"/k8s_curl_demo-curl-f7f7d86c-w9zss_chaos_d935dd80-5b1c-4bfe-a913-c593b91aff29_0"}
{"level":"info","ts":1624459766544.775,"caller":"injector/main.go:154","message":"injector targeting container","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss","containerID":"docker://4b533ab35f2e2c0e897cdfcbbc3505d819850cd22848b5e1e4da036745eb8176","container name":"/k8s_dummy_demo-curl-f7f7d86c-w9zss_chaos_d935dd80-5b1c-4bfe-a913-c593b91aff29_0"}
{"level":"info","ts":1624459766545.6682,"caller":"injector/main.go:228","message":"injecting the disruption","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766545.6929,"caller":"injector/network_disruption.go:77","message":"adding network disruptions","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss","drop":100,"duplicate":0,"corrupt":0,"delay":0,"delayJitter":0,"bandwidthLimit":0}
{"level":"info","ts":1624459766546.0093,"caller":"injector/network_disruption.go:193","message":"detected default gateway IP 169.254.1.1 on interface eth0","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766546.0254,"caller":"injector/network_disruption.go:201","message":"target pod node IP is 10.1.77.165","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766547.3503,"caller":"injector/network_disruption.go:220","message":"setting tx qlen for interface eth0","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766547.503,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev eth0 root handle 1: prio bands 4 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766548.8694,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev lo root handle 1: prio bands 4 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766550.0566,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev eth0 parent 1:4 handle 2: prio bands 2 priomap 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766551.1255,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev lo parent 1:4 handle 2: prio bands 2 priomap 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766552.1704,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev eth0 parent 2:0 handle 2: cgroup","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766553.1016,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev lo parent 2:0 handle 2: cgroup","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766553.9832,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev eth0 parent 2:2 handle 3: netem loss 100%","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766554.9204,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc qdisc add dev lo parent 2:2 handle 3: netem loss 100%","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766555.9028,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev eth0 parent 1:0 u32 match ip dst 0.0.0.0/0 match ip dport 80 0xffff flowid 1:4","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766556.871,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev lo parent 1:0 u32 match ip dst 0.0.0.0/0 match ip dport 80 0xffff flowid 1:4","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766557.8008,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev eth0 parent 1:0 u32 match ip dst 169.254.1.1/32 flowid 1:1","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766558.7136,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev eth0 parent 1:0 u32 match ip dst 10.1.77.165/32 flowid 1:1","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766559.6082,"caller":"network/tc.go:63","message":"running tc command: /sbin/tc filter add dev lo parent 1:0 u32 match ip dst 10.1.77.165/32 flowid 1:1","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766560.5198,"caller":"injector/network_disruption.go:229","message":"clearing tx qlen for interface eth0","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766560.6428,"caller":"injector/network_disruption.go:97","message":"operations applied successfully","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766560.682,"caller":"injector/network_disruption.go:100","message":"editing pod net_cls cgroup to apply a classid to target container packets","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
NOOP: MetricInjected true
{"level":"info","ts":1624459766560.8398,"caller":"injector/main.go:243","message":"disruption injected, now waiting for an exit signal","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
{"level":"info","ts":1624459766560.8535,"caller":"injector/network_disruption.go:77","message":"adding network disruptions","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss","drop":0,"duplicate":0,"corrupt":0,"delay":0,"delayJitter":0,"bandwidthLimit":0}
{"level":"info","ts":1624459766560.8652,"caller":"injector/network_disruption.go:100","message":"editing pod net_cls cgroup to apply a classid to target container packets","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
NOOP: MetricInjected true
{"level":"info","ts":1624459766562.023,"caller":"injector/main.go:243","message":"disruption injected, now waiting for an exit signal","disruptionName":"network-ingress","disruptionNamespace":"chaos","targetName":"demo-curl-f7f7d86c-w9zss"}
```

I cannot see anything different though. The demo-curl pod can still call Nginx.

I tried many different pod level disruptions including the one above but for ingress traffic, or even disrupting the Service:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-filters
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  network:
    drop: 100
    // with and without flow: ingress
    services:
      - name: demo
        namespace: chaos
```

I also attempted to verify the impact by port-forwarding (the service/deployment/pod of) the Nginx server and the curl-demo app and then hitting the url, or by using `nc`, but still nothing.

**Expected behavior**
Impact is visible.

**Screenshots**

**Environment:**
 - Kubernetes version: EKS 1.19
 - Controller version: 4.0.1
 - Cloud provider (or `local`): AWS
 - Base OS for Kubernetes: docker://19.3.13

**Comment by Devatoria** [comment]
For the first disruption manifest you provided, you are disrupting port `80` but the service port is `8080`. Have you tried the exact same disruption but with port `8080` instead? At the pod level, the packets are not yet NATed to the endpoint port so the destination port (and IP) is still the service one and not the endpoint one.

For the second example, with service disruption, it should work though (at least it works on Minikube and in our clusters). What is your kube-proxy configuration (at least which implementation, `ipvs` or `iptables`?).

**Comment by nikos912000** [comment]
Yup. I tried with 8080 as well but still not impact.

The cluster is in the `iptables` mode from what I can see:
```
{
  "config": "apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: \"\"
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig
      qps: 5
    clusterCIDR: \"\"
    configSyncPeriod: 15m0s
    conntrack:
      max: 0
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: \"\"
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: \"\"
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 127.0.0.1:10249
    mode: \"iptables\"
    nodePortAddresses: null
    oomScoreAdj: -998
    portRange: \"\"
    udpIdleTimeout: 250ms"
}
```

**Comment by Devatoria** [comment]
Ok thanks. As a sanity check, does it work if you drop all outgoing traffic of the pod (without specifying the `hosts` or `services` fields, only `drop: 100`)? So I know if it is related to filters or the disruption injection itself.

Also I don't know how much you feel comfortable with networking tools but I'd definitely like to have a small `tcpdump` extract from within the targeted pod network namespace to see how packets are sent over the network and why they would eventually not be filtered. I can try to give you some guidance about how to do it if you are not sure.

**Comment by nikos912000** [comment]
Thanks @Devatoria 
`does it work if you drop all outgoing traffic of the pod`, no same issue unfortunately.
As regards the tcpdump let me check what I can do.

**Comment by nikos912000** [comment]
Here is the latest Disruption:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-all
  namespace: chaos
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  network:
    drop: 100
```

While this was running I took the following tcpdump (all interfaces) from the `curl-demo` pod (`dummy` container):
[tcpdump.txt](https://github.com/DataDog/chaos-controller/files/6703744/tcpdump.txt)
