### ISSUE TITLE
User Issue: injector panics due to cgroupPaths containing an empty string

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#409]
**Describe the bug**
While working on #405 I came across an issue in the main branch where the injector panics when retrieving the [cgroupPaths](https://github.com/DataDog/chaos-controller/blob/feaeb6e675327740a76bc56caa182ae11d9a47cb/cli/injector/main.go#L200).

**To Reproduce**
Steps to reproduce in minikube:
1. `make minikube-start`
2. `make minikube-build`; make sure the new images are not cached by either destroying minikube or using the [old Makefile](https://github.com/DataDog/chaos-controller/blob/d0dfcf8c8bdd20d580c8aee7c46c1fc37f07af72/Makefile#L70). In the `main` branch's Makefile images are always cached for me.
3. `make install`
4. `make restart`
5. Deploy the following Disruption:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: dns
  namespace: chaos-engineering
spec:
  level: node
  selector:
    kubernetes.io/hostname: minikube
  count: 100%
  dns:
    - hostname: demo.chaos-demo.svc.cluster.local
      record:
        type: A
        value: 10.0.0.154,10.0.0.13
```

The chaos-dns pod gets created but panics:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.initConfig()
/Users/nkatirtzis/github/chaos-controller/cli/injector/main.go:206 +0x16df
```

**Expected behavior**
The chaos-dns pods successfully injects the failure.

**Environment:**
 - Kubernetes version: 1.19.14
 - Controller version: latest (feaeb6e675327740a76bc56caa182ae11d9a47cb)
 - Cloud provider (or `local`): minikube
 - Base OS for Kubernetes: minikube with containerd

**Additional context**
From the logs I could see the [cgroupPaths](https://github.com/DataDog/chaos-controller/blob/feaeb6e675327740a76bc56caa182ae11d9a47cb/cli/injector/main.go#L199) being a list with only an empty string.
