### ISSUE TITLE
User Issue: Injector Pod stuck in Failed phase with reason DeadlineExceeded

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#491]
**Describe the bug**
We have been intermittently running into an issue where the injector Pod gets stuck in the `Failed` phase with the following context:
```
status:
  phase: Failed
  message: Pod was active on the node longer than the specified deadline
  reason: DeadlineExceeded
```

**Deployed Disruption**
Note: We didn't set the duration when applying the Disruption. This defaults to 15 mins which is reflected in the CR.
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: container-failure
  namespace: chaos-engineering
spec:
  selector:
    app: demo-nginx
  count: 1
  containerFailure:
    forced: true
```

**Disruption specs**
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  creationTimestamp: '2022-02-01T15:28:39Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2022-02-01T15:58:43Z'
  finalizers:
    - finalizer.chaos.datadoghq.com
  generation: 7
  ...
status:
  ignoredTargets:
    - XXX
  injectionStatus: PreviouslyInjected
spec:
  containerFailure:
    forced: true
  count: 1
  duration: 15m0s
  selector:
    app: XXX
```

**Injector Pod specs**
The finaliser gets successfully removed but the Pod is still there.
```
apiVersion: v1
kind: Pod
metadata:
  ...
  creationTimestamp: '2022-02-01T15:28:40Z'
  deletionTimestamp: '2022-02-01T15:44:39Z'
  deletionGracePeriodSeconds: 60
  ...
status:
  phase: Failed
  message: Pod was active on the node longer than the specified deadline
  reason: DeadlineExceeded
  startTime: '2022-02-01T15:28:40Z'
  containerStatuses:
    - name: injector
      state:
        running:
          startedAt: '2022-02-01T15:28:42Z'
      lastState: {}
      ready: false
      restartCount: 0
    - name: XXX
      state:
        running:
          startedAt: '2022-02-01T15:28:42Z'
      lastState: {}
      ready: false
      restartCount: 0
  qosClass: Burstable
spec:
  ...
  terminationGracePeriodSeconds: 60
  activeDeadlineSeconds: 899
  ...
```

**Injector Pod logs**
(reconstructed from our logging platform)
```
injector targeting container
injector targeting container
injecting the disruption
injecting a container failure
disruption container-failure injected
injecting a container failure
disruption container-failure injected
disruption(s) injected, now waiting for an exit signal
an exit signal has been received
disruption container-failure cleaned
disruption container-failure cleaned
disruption(s) cleaned, now exiting
closing metrics sink client before exiting
```

**To Reproduce**
Unfortunately I don't have a way to reproduce this consistently...

**Expected behavior**
The injector Pod and the Disruption get deleted.

**Environment:**
 - Kubernetes version: 1.20.11
 - Controller version: 5.2.1
 - Cloud provider (or `local`): EKS
 - Base OS for Kubernetes: Amazon Linux 2
 - Container runtime: docker
