### ISSUE TITLE
User Issue: Injector Pod stuck when executing kernel panic disruption

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#495]
**Describe the bug**
I have been executing kernel panic attacks and the injector Pod gets stuck in the `Terminating` state (`exit code: 255`).
The controller is not able to remove its finalizer and eventually to clean up the injector Pod and the Custom Resource. It logs the following:
```
{"level":"info","ts":1643818006815.9573,"caller":"controllers/disruption_controller.go:628","message":"instance seems stuck on removal for this target, please check manually","instance":"node-failure","namespace":"chaos-engineering-framework","target":"ip-10-72-9-223.us-west-2.compute.internal","chaosPod":"chaos-node-failure-2z6tw"}

NOOP: Notifier Warning: StuckOnRemoval - Instance is stuck on removal because of chaos pods not being able to terminate correctly, please check pods logs before manually removing their
```

I was wondering if this is expected.

In node terminations this is not an issue as the Pod will get evicted once the Node gets replaces.

**Deployed Disruption**
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: node-failure
  namespace: chaos-engineering-framework
spec:
  duration: 3m
  level: node
  selector:
    kubernetes.io/hostname: <hostname>
  count: 100%
  nodeFailure:
    shutdown: false
```

**Disruption specs**
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  ...
  creationTimestamp: '2022-02-04T17:01:20Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2022-02-04T17:14:26Z'
  finalizers:
    - finalizer.chaos.datadoghq.com
  generation: 7
  ...
status:
  ignoredTargets:
    - <hostname>
  injectionStatus: PreviouslyInjected
  isStuckOnRemoval: true
  ...
spec:
  count: 100%
  duration: 3m0s
  level: node
  nodeFailure: {}
  selector:
    kubernetes.io/hostname: <hostname>
```

**Injector Pod specs**
```
apiVersion: v1
kind: Pod
metadata:
  ...
  creationTimestamp: '2022-02-04T17:01:20Z'
  deletionTimestamp: '2022-02-04T17:14:26Z'
  deletionGracePeriodSeconds: 0
  ...
  finalizers:
    - finalizer.chaos.datadoghq.com/chaos-pod
  ...
status:
  phase: Failed
  ...
  startTime: '2022-02-04T17:01:20Z'
  ...
  containerStatuses:
    - name: injector
      state:
        terminated:
          exitCode: 255
          reason: Error
          startedAt: '2022-02-04T17:01:23Z'
          finishedAt: '2022-02-04T17:01:54Z'
          containerID: >-
            docker://<id>
      lastState: {}
      ready: false
      restartCount: 0
      ...
      started: false
    ...
  qosClass: Burstable
spec:
  ...
  containers:
    - name: injector
      ...
      args:
        - node-failure
        - inject
        - '--metrics-sink'
        - datadog
        - '--level'
        - node
        - '--target-container-ids'
        - ''
        - '--target-pod-ip'
        - ''
        - '--chaos-namespace'
        - chaos-engineering-framework
        - '--log-context-disruption-name'
        - node-failure
        - '--log-context-disruption-namespace'
        - chaos-engineering-framework
        - '--log-context-target-name'
        - <hostname>
        - '--log-context-target-node-name'
        - <hostname>
        - '--deadline'
        - '2022-02-04T17:04:19Z'
      env:
        - name: TARGET_POD_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CHAOS_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: INJECTOR_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CHAOS_INJECTOR_MOUNT_HOST
          value: /mnt/host/
        - name: CHAOS_INJECTOR_MOUNT_PROC
          value: /mnt/host/proc/
        - name: CHAOS_INJECTOR_MOUNT_SYSRQ
          value: /mnt/sysrq
        - name: CHAOS_INJECTOR_MOUNT_SYSRQ_TRIGGER
          value: /mnt/sysrq-trigger
        - name: CHAOS_INJECTOR_MOUNT_CGROUP
          value: /mnt/cgroup/
        ...
      ...
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/readiness_probe
        timeoutSeconds: 1
        periodSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      ...
    ...
  restartPolicy: Never
  terminationGracePeriodSeconds: 60
  activeDeadlineSeconds: 189
  dnsPolicy: ClusterFirst
  serviceAccountName: chaos-injector
  serviceAccount: chaos-injector
  nodeName: <hostname>
  ...

```

**Expected behavior**
Injector Pods and Disruption get cleaned up once the Disruption expires.

**Environment:**
- Kubernetes version: 1.20.11
- Controller version: 5.2.1
- Cloud provider (or `local`): EKS
- Base OS for Kubernetes: Amazon Linux 2
- Container runtime: docker
