### ISSUE TITLE
User Request: store failures in the Custom Resource's status

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#542]
**Is your feature request related to a problem? Please describe.**
To improve developer experience we are integrating the controller with our Continuous Delivery platform. Since any failures are only logged in the controller showing that feedback in the UI is not trivial.

**Describe the solution you'd like**
It would be helpful to store any errors related to a specific experiment in the Custom Resource's status. Any clients can then fetch these errors from the CR (and show these in the UI).

```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
...
status:
  injectionStatus: NotInjected
  errors: "invalid disruption name"
  targets:
    - demo-nginx-68954564c-pfxc8
spec:
  containerFailure:
    forced: true
  count: 1
  duration: 1m30s
  selector:
    app: demo-nginx
```

**Describe alternatives you've considered**
We are open to ideas if there is a better way to show that information in a user interface. An alternative is to associate logs with experiments but this is still not trivial.
